etesync/etesync-web

src/widgets/ExternalLink.tsx

Please verify yourself, whether this actually works. I've just modified this based on looking at the source.

Add access prohibition for external links

---

public/index.html

I guess this won't hurt for privacy, even if there is no referrer on the page. :smile:

Disable referrer when clicking links

---

src/App.tsx
src/Journals/JournalsListImport.tsx
src/Journals/index.tsx
src/SideMenu/index.tsx

Journal Import: add an import link to the sidebar

---

src/Journals/JournalEdit.tsx
src/Journals/JournalsList.tsx
src/Journals/JournalsListImport.tsx
src/widgets/ColorBox.tsx
src/widgets/ColorPicker.tsx

JournalEdit: add ColorPicker and imporve validation 

---

src/components/Tasks/TaskEdit.tsx
src/components/Tasks/TaskListItem.tsx
src/helpers.tsx
src/pim-types.ts
src/widgets/ColoredRadio.tsx

including Colored Radio buttons, colored checkboxes

Tasks: adds priority functionality

---

src/Journals/JournalsList.tsx

JournalsList: add icon to titles

---

src/components/Tasks/TaskEdit.tsx

I assume this is just some cruft from a bad copy-paste

Tasks: renames some vars from event to task

---

src/components/Tasks/TaskListItem.tsx

a const was accidentally placed in the middle of imports,
that has been moved

Tasks: moves misplaced const

---

src/components/Tasks/Sidebar.tsx
src/components/Tasks/TaskList.tsx
src/pim-types.ts

cleans up some code around filtering by due today

Tasks: adds dueToday getter to TaskType

---

src/components/Tasks/Toolbar.tsx
src/widgets/Menu.tsx

Menus previously blocked menu buttons

Tasks: improves positioning of Toolbar menus

---

package.json
src/widgets/TimezonePicker.tsx
yarn.lock

I would like to use the new [Alert](https://material-ui.com/components/alert/#alert) component for  displaying error messages. This requires an update of mui/lab and mui/core

Update mui lab dependency

---

src/components/EventEdit.tsx
src/components/Tasks/TaskEdit.tsx
src/widgets/Toast.tsx

Add Toast component for displaying error messages in a more prominent way

UI: pretty error messages

---

src/pim-types.ts

pim-types: change clone to deep clone using to/fromString

---

src/Pim/PimMain.tsx
src/Pim/index.tsx
src/components/Tasks/TaskEdit.tsx
src/components/Tasks/TaskList.tsx
src/components/Tasks/TaskListItem.tsx
src/etesync-helpers.ts
src/pim-types.ts
src/types/ical.js.d.ts
src/widgets/Toast.tsx

Tasks: support reccuring tasks

---

src/App.tsx

Implement an auto refresh function that calls fetchAll every minute if the user is online and logged in.
Fixes #28

Automatic refresh

---

src/components/ContactEdit.tsx
src/pim-types.ts

Split name field

---

src/App.tsx
src/Pim/index.tsx
src/components/EventEdit.tsx

Implement Event copying

---

src/App.tsx
src/Pim/index.tsx
src/components/EventEdit.tsx

This is the new [icon](https://material.io/resources/icons/?search=insert_inv&icon=insert_invitation&style=baseline).

Change 'copy' to 'duplicate' and switch to more appropriate icon

---

src/Settings/index.tsx
src/SyncGate.tsx
src/helpers.tsx
src/pim-types.ts
src/store/reducers.ts

Hello, I am back! My last PR was a bit messy so I decided to make a new one.
This time I created the fake journal as you suggested.
The hideBirthday setting gets passed to Pim as a prop so it re-renders now.
The birthday calendar events are now clickable but the edit/duplicate buttons are disabled.
Fixes #77

Birthday calendar 2

---

src/App.tsx
src/Contacts/ContactEdit.tsx
src/Contacts/GroupEdit.tsx
src/Contacts/Main.tsx
src/Contacts/SearchableAddressBook.tsx
src/Contacts/Sidebar.tsx
src/widgets/List.tsx

The basic functionality requested in #136 is here: creating/editing/deleting groups and adding/removing members.
The UI still needs some work, but this should work for now.

Contacts: Add basic group editing functionality

---

src/Contacts/ContactEdit.tsx

Mixed up an array with a generic Object at one point, leading to line 365 always being true.

ContactEdit: fix contacts getting added to groups multiple times
